### ISSUE TITLE
Breaking changes in dependency

### ISSUE THREAD

**Issue by sahlex** [Stutchbury/EventButton#1]
Version 1.0.2 depends on Bounce2:2.60.0 which does not implement currentDuration() that was introduced in Version 2.70. So the build breaks...

Please change dependency to Bounce2:2.70

**Comment by Stutchbury** [comment]
Thanks sahlex - not quite sure why I didn't create the release when I updated the dependency...
New release v1.0.3 created and published to pio. The Arduino Library Manager should pick it up.
